### ISSUE TITLE
Lack of method to extract data after embedding payload?

### ISSUE THREAD

**Issue by DarkAngel-Khei** [masterjeef/stego-sharp#5]
Hi, I just wanted to reach out if there is a lack of a method to extract data after a string/file has been hidden into an image file. 

I've looked through the class and methods, and I don't see any related method that will read hidden data from an image with prior hidden data. 

Please let me know if this is intentional or I have miss-looked, thanks in advance.

**Comment by masterjeef** [comment]
There are some examples in the unit tests where I write and read data into an image. The method you're probably looking for is `ExtractBytes`.

            using (var imageWithMessage = new StegoImage(resultPath))
            {
               var embeddedString = Encoding.Default.GetString(imageWithMessage.ExtractBytes().ToArray());
               var embedded = embeddedString.Substring(0, message.Length);
               Assert.Equal(message, embedded);
            }

**Comment by DarkAngel-Khei** [comment]
Cheers, thanks a lot for the prompt feedback and example

**Comment by cblaze22** [comment]
This just does not work.  I am getting ```‰PNG\r\n\u001a\n\0\0\0\rIHDR\0``` as the output for embedded?

```
 public static void ApplyStego(string imagePath, string destinationPath)
 {
     using (var image = new StegoImage(imagePath))
     {
         image.EmbedPayload(Config.Settings.WatermarkText).Save(destinationPath);
     }
 }

 public static bool HasStego(Stream stream)
 {
     using (var memoryStream = new MemoryStream())
     {
         stream.CopyTo(memoryStream);
         var embeddedString = Encoding.Default.GetString(memoryStream.ToArray());
         var embedded = embeddedString.Substring(0, Config.Settings.WatermarkText.Length);
         stream.Position = 0;
         return Config.Settings.WatermarkText.Equals(embedded);
     }
 }
```
