### ISSUE TITLE
Constructor with stream input

### ISSUE THREAD

**Issue by cblaze22** [masterjeef/stego-sharp#6]
We cant add stego watermarks to a file upload because there is no constructor for this project that takes a stream, only a path.  Can we get that with another nuget really quick?

**Comment by masterjeef** [comment]
@cblaze22 I was out of town when I got this, and it slipped through the cracks. I've added a constructor that accepts a Bitmap. You can pass a Stream into the Bitmap constructor similar to this (except you would pass a different type of Stream):
```
using (FileStream fileStream = new FileStream("some-file.png", FileMode.Open, FileAccess.Read))
using (var image = new StegoImage(new Bitmap(fileStream)))
{
                image.EmbedPayload(message)
                    .Save(resultPath);
}
```
I've published a new package to Nuget as well.

**Comment by cblaze22** [comment]
Awesome! Will test this week!

Mike
